name: Web Deploy CI

on: 
  push:
    branchs:
     - main
     
jobs:
  build:
    runs-on: ubuntu-18.04
    
steps:
- name: Deploy using ssh
  uses: apple
  
  https://dev.to/knowbee/how-to-setup-continuous-deployment-of-a-website-on-a-vps-using-github-actions-54im
  
  https://gist.github.com/danielwetan/4f4db933531db5dd1af2e69ec8d54d8a