name: Web Deploy CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_BAND_SCHEDULE }}
          username: ${{ secrets.USERNAME_BAND_SCHEDULE }}
          port: ${{ secrets.PORT_BAND_SCHEDULE }}
          password: ${{ secrets.PASSWORD_BAND_SCHEDULE}}
          script: ls
